server:
  port: 8081

eureka:
  server:
    renewalPercentThreshold: 0.70
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    fetch-registry: false
    register-with-eureka: false
